version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "NodeWebsocketServerless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ofzl7wzb2qgl"
s3_prefix = "NodeWebsocketServerless"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"chats\""
